version: '3'
services:
  # 默认账户密码 admin/admin
  grafana:
    image: grafana/grafana:6.5.0
    container_name: grafana
    logging:
      driver: “json-file”
      options:
        max-size: “500m”
    environment:
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
    volumes:
      - ./conf/grafana/plugins:/var/lib/grafana/plugins
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
