version: '3'
services:
  redis:
    image: redis:5
    container_name: redis5
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
#volumes:
#  redis-data:
#    driver_opts:
#      type: none
#      device:  ./data/redis/data
#      o: bind
#networks:
#  dataease-network:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.19.0.0/16
#          gateway: 172.19.0.1