version: '3'
services:
  redis5-master:
    image: redis:5
    container_name: redis5-master
    # network_mode: redis-sentinel
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    # 指定时区，保证容器内时间正确
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./conf/redis-sentinel/server/redis5-master.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis-sentinel/redis5-master/data:/data #数据文件挂载
    ports:
      - 6379:6379
  redis5-slave1:
    image: redis:5
    container_name: redis5-slave1
    # network_mode: redis-sentinel
    depends_on:
      - redis5-master
    command:  ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./conf/redis-sentinel/server/redis5-slave1.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis-sentinel/redis5-slave1/data:/data #数据文件挂载
    ports:
      - 6380:6379
  redis5-slave2:
    image: redis:5
    container_name: redis5-slave2
    # network_mode: redis-sentinel
    depends_on:
      - redis5-master
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./conf/redis-sentinel/server/redis5-slave2.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis-sentinel/redis5-slave2/data:/data #数据文件挂载
    ports:
      - 6381:6379

  redis-sentinel-1:
    image: redis:5
    container_name: redis-sentinel-1
    # network_mode: redis-sentinel
    depends_on:
      - redis5-master
      - redis5-slave1
      - redis5-slave2
    volumes:
      - ./conf/redis-sentinel/sentinel/redis5-sentinel-1.conf:/usr/local/etc/redis/redis-sentinel.conf
    ports:
      - 26379:26379
    environment:
      TZ: "Asia/Shanghai"
    sysctls:
      net.core.somaxconn: '511'
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]
  redis-sentinel-2:
    image: redis:5
    container_name: redis-sentinel-2
    # network_mode: redis-sentinel
    depends_on:
      - redis5-master
      - redis5-slave1
      - redis5-slave2
    volumes:
      - ./conf/redis-sentinel/sentinel/redis5-sentinel-2.conf:/usr/local/etc/redis/redis-sentinel.conf
    ports:
      - 26380:26379
    environment:
      TZ: "Asia/Shanghai"
    sysctls:
      net.core.somaxconn: '511'
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]
  redis-sentinel-3:
    image: redis:5
    container_name: redis-sentinel-3
    # network_mode: redis-sentinel
    depends_on:
      - redis5-master
      - redis5-slave1
      - redis5-slave2
    volumes:
      - ./conf/redis-sentinel/sentinel/redis5-sentinel-3.conf:/usr/local/etc/redis/redis-sentinel.conf
    ports:
      - 26381:26379
    environment:
      TZ: "Asia/Shanghai"
    sysctls:
      net.core.somaxconn: '511'
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]


