# https://time.geekbang.org/column/article/40466
apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume
spec:
  containers:
    - name: test-secret-volume
      image: busybox
      args:
        - sleep
        - "86400"
      volumeMounts:
        - name: mysecret
          mountPath: "/projected-volume"
          readOnly: true
  volumes:
    - name: mysecret
      projected:
        sources:
          - secret:
              name: user
          - secret:
              name: pass